site_name: Devops Culture
theme:
  name: material
  # logo: assets/devops-culture.png
  icon:
    repo: fontawesome/brands/github 
  font:
    code: Ubuntu
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
  plugins:
    - search
    - search.suggest
    - search.highlight
    - git-revision-date-localized:
        enable_creation_date: true
        type: date
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: deep purple
repo_url: https://github.com/devops-culture-project/devops-culture.git
repo_name: devops-culture-project