# Project Information
site_name: Devops Culture
site_url: https://devops-culture-project.github.io/devops-culture
site_author: Itamar Marom
site_description: >-
  Devops Culture provides software engineers with one place that holds a wide variety of concepts, 
  ideas, and tools related to software and its eco-system.

# Repository
repo_url: https://github.com/devops-culture-project/devops-culture
repo_name: devops-culture-project

# Copyright
copyright: Copyright &copy; 2020 - 2022 Itamar Marom

# Configuration
theme:
  name: material
  logo: assets/devops-culture.png
  icon:
    repo: fontawesome/brands/github 
  font:
    code: Ubuntu
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    # - header.autohide
    - announce.dismiss
  #   - content.code.annotate
  #   - content.tooltips

  plugins:
    - search
    - social
    - git-revision-date-localized:
        enable_creation_date: true
    - git-committers:
        repository: devops-culture-project/devops-culture
    - git-authors
    # - minify:
    #     minify_html: true
    # - glightbox

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/devops-culture-project
      name: Devops Culture on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/itamar-marom
      name: Itmaar Marom on LinkedIn

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: devops-culture-project
      repo: devops-culture